#!/bin/bash

# USAGE:
#   Run `./versions TAG` where TAG is the tagged image version you want to check
#   the information of every package.


BASE="docker run -ti --rm devdrops/php-toolbox:$1"

eval "$BASE php --version"
eval "$BASE composer --version"
eval "$BASE phpunit --version"
eval "$BASE phpcs --version"
eval "$BASE php-cs-fixer --version"
eval "$BASE phpmd --version"
eval "$BASE behat --version"
eval "$BASE phploc --version"
eval "$BASE phpstan --version"
eval "$BASE psalm --version"

